# Site Settings
title: 赵醒醒的个人博客
email: 757032662@qq.com
description: 记录生活学习中的一些经历.
baseurl: ''
url: "https://zhaoxxxx.github.io" # the base hostname & protocol for your site


# User Settings
username: zhaoxxxx
user_description: qqqqqqqqqq.


# Social Media
# Remove the item if you don't need it
github_username: zhaoxxxx


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
